### PR TITLE
Mholman5721

### PR DESCRIPTION
**Pull request by mholman5721**
This Pull request includes layout modifications to the toolbox. However, there are several things that need to be fixed:
    - toolbox should be the exact width of the QColorDialog widget
    - time counters should be in M:S:MS, not H:M.S as it is now
    - spin boxes should be able to enter values > two digits big (range 0 - 255)
These are all easy fixes, and I will get on them as soon as I can. Other than that, the signals/ slots work so we can at least add functionality now.

### CODE REVIEW

**Comment by trevmo** [comment]
Suggested changes:
- Modify add frames in toolbox so that the user can specify an insertion index and number of frames instead of start and end positions.
- Update the range of the insertion index input element according to the number of frames in the animation. (See getNumFrames() in animation.h)
- Ensure that times are input in mm:ss.ms format, not hh:mm:ss.
- Search for predefined method that converts that time to milliseconds.

**Comment by mholman5721** [comment]
Added a default value to the 'time interval' box - the current time box will need to be calculated based on the positions/ time values of adjacent frames.

The logic for add frames/ delete frames is seemingly good - however the logic for copy frames needs some work. Specifically, if the user tries to move the start index beyond the end index, the end index should increment as well. Vice/ versa, if the user tries to move the end index before the start index, the start index should decrement. Additionally, when copying, if the insertion index falls between the start/ end index, the frames in the range should be copied entirely first, and then inserted - doing otherwise might cause unexpected copying behavior in the form of frames being duplicated multiple times:

1 2 [3 4 i 5 6] 7 8 9 10 => 1 2 3 4 3 4 3 4 5 6 7 8 9 10, instead of 1 2 3 4 3 4 5 6 5 6 7 8 9 10 as expected.

**Comment by mholman5721** [comment]
Incorporated the Doxygen comments from Domanic's branch.

**Comment by trevmo** [comment]
Toolbox incorporated with other changes.

**Pull request closed without merging**
