### PR TITLE
editor mockup and section documentation

### PR DESCRIPTION
**Pull request by trevmo**
- added directory for mockups
- added initial mockup of the editor section
- updated editor.tex to include documentation for the section

### CODE REVIEW

**Comment by trevmo** [comment]
@fetr0509 If you could take a look at this by 3pm today, that'd be great. Otherwise, I will just merge it in without a review. (Despite being an "admin," I'd appreciate having someone review my changes.)

**Comment by fetr0509** [comment]
Will do. Sorry I had an interview this morning so I've been holding off on doing this assignment but I'll make sure to give it a look before 3:00.

**Comment by trevmo** [comment]
Ok, no worries. Thanks!

**Comment by fetr0509** [comment]
When I run this through my LaTex program it give me errors. Did you get this to run without errors?

**Comment by fetr0509** [comment]
Looks good

**Pull request merged**
